apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unit-converter-role
  namespace: unit-converter
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
